// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// logit_linkinv
NumericVector logit_linkinv(NumericVector eta);
RcppExport SEXP estimtr_logit_linkinv(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    __result = Rcpp::wrap(logit_linkinv(eta));
    return __result;
END_RCPP
}
